/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/CLmPPiWyUsp
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Tenor_Sans } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

tenor_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Sheet, SheetTrigger, SheetContent } from "@/components/ui/sheet"
import Link from "next/link"

export function course() {
  return (
    <div className="grid grid-cols-1 md:grid-cols-[1fr_300px] gap-6 w-full h-full">
      <div className="relative aspect-video rounded-lg overflow-hidden">
        <video
          className="w-full h-full object-cover"
          src="https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
          controls
        />
        <div className="absolute top-4 left-4 z-10">
          <Button variant="ghost" size="icon" className="bg-black/50 hover:bg-black/75 text-white">
            <MaximizeIcon className="w-5 h-5" />
            <span className="sr-only">Fullscreen</span>
          </Button>
        </div>
      </div>
      <div className="bg-background border-l rounded-lg overflow-hidden">
        <Sheet>
          <SheetTrigger asChild>
            <Button variant="ghost" size="icon" className="absolute top-4 right-4 z-10 bg-background hover:bg-muted">
              <MenuIcon className="w-5 h-5" />
              <span className="sr-only">Toggle sidebar</span>
            </Button>
          </SheetTrigger>
          <SheetContent side="right" className="w-full md:w-[300px] h-full">
            <div className="flex flex-col h-full">
              <div className="border-b p-4">
                <h2 className="text-xl font-semibold">Video Series</h2>
              </div>
              <div className="flex-1 overflow-auto">
                <nav className="grid gap-2 p-4">
                  <Link
                    href="#"
                    className="flex items-center gap-3 rounded-md bg-muted px-3 py-2 text-primary transition-colors hover:bg-muted/50"
                    prefetch={false}
                  >
                    <div className="flex-shrink-0">
                      <img
                        src="/placeholder.svg"
                        width={48}
                        height={48}
                        alt="Thumbnail"
                        className="rounded-md object-cover"
                      />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="font-medium line-clamp-1">Introduction to React</div>
                      <div className="text-sm text-muted-foreground line-clamp-1">1. Getting Started</div>
                    </div>
                  </Link>
                  <Link
                    href="#"
                    className="flex items-center gap-3 rounded-md bg-muted px-3 py-2 text-primary transition-colors hover:bg-muted/50"
                    prefetch={false}
                  >
                    <div className="flex-shrink-0">
                      <img
                        src="/placeholder.svg"
                        width={48}
                        height={48}
                        alt="Thumbnail"
                        className="rounded-md object-cover"
                      />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="font-medium line-clamp-1">React Components</div>
                      <div className="text-sm text-muted-foreground line-clamp-1">2. Building Components</div>
                    </div>
                  </Link>
                  <Link
                    href="#"
                    className="flex items-center gap-3 rounded-md bg-muted px-3 py-2 text-primary transition-colors hover:bg-muted/50"
                    prefetch={false}
                  >
                    <div className="flex-shrink-0">
                      <img
                        src="/placeholder.svg"
                        width={48}
                        height={48}
                        alt="Thumbnail"
                        className="rounded-md object-cover"
                      />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="font-medium line-clamp-1">React State Management</div>
                      <div className="text-sm text-muted-foreground line-clamp-1">3. Managing State</div>
                    </div>
                  </Link>
                  <Link
                    href="#"
                    className="flex items-center gap-3 rounded-md bg-muted px-3 py-2 text-primary transition-colors hover:bg-muted/50"
                    prefetch={false}
                  >
                    <div className="flex-shrink-0">
                      <img
                        src="/placeholder.svg"
                        width={48}
                        height={48}
                        alt="Thumbnail"
                        className="rounded-md object-cover"
                      />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="font-medium line-clamp-1">React Routing</div>
                      <div className="text-sm text-muted-foreground line-clamp-1">4. Routing in React</div>
                    </div>
                  </Link>
                  <Link
                    href="#"
                    className="flex items-center gap-3 rounded-md bg-muted px-3 py-2 text-primary transition-colors hover:bg-muted/50"
                    prefetch={false}
                  >
                    <div className="flex-shrink-0">
                      <img
                        src="/placeholder.svg"
                        width={48}
                        height={48}
                        alt="Thumbnail"
                        className="rounded-md object-cover"
                      />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="font-medium line-clamp-1">React Hooks</div>
                      <div className="text-sm text-muted-foreground line-clamp-1">5. Using Hooks</div>
                    </div>
                  </Link>
                </nav>
              </div>
            </div>
          </SheetContent>
        </Sheet>
        <div className="flex items-center justify-between border-t p-4">
          <Button variant="ghost" size="icon" className="text-muted-foreground hover:bg-muted">
            <ArrowLeftIcon className="w-5 h-5" />
            <span className="sr-only">Previous</span>
          </Button>
          <Button variant="ghost" size="icon" className="text-muted-foreground hover:bg-muted">
            <ArrowRightIcon className="w-5 h-5" />
            <span className="sr-only">Next</span>
          </Button>
        </div>
      </div>
    </div>
  )
}

function ArrowLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </svg>
  )
}


function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}


function MaximizeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 3H5a2 2 0 0 0-2 2v3" />
      <path d="M21 8V5a2 2 0 0 0-2-2h-3" />
      <path d="M3 16v3a2 2 0 0 0 2 2h3" />
      <path d="M16 21h3a2 2 0 0 0 2-2v-3" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
